namespace Vex.Modules.Workspace.Services;

internal sealed record MarkdownExportStyle(
    string BodyFontFamily,
    string MonoFontFamily,
    double BodyFontSize,
    double Heading1FontSize,
    double Heading2FontSize,
    double Heading3FontSize,
    double Heading4FontSize,
    double Heading5FontSize,
    double Heading6FontSize,
    double CodeFontSize,
    double TableFontSize,
    double LineHeightRatio,
    string PageBackgroundColor,
    string BodyColor,
    string HeadingColor,
    string MutedColor,
    string BorderColor,
    string CodeBackgroundColor,
    string CodeForegroundColor,
    string InlineCodeBackgroundColor,
    string InlineCodeForegroundColor,
    string LinkColor,
    string TableHeaderBackgroundColor,
    string QuoteBorderColor)
{
    private const string DefaultBodyFontFamily = "Inter, Microsoft YaHei UI, Segoe UI";
    private const string DefaultMonoFontFamily = "Cascadia Mono, Consolas";
    private const string CompactTypographySize = "Small";

    public static MarkdownExportStyle Resolve(string? typographyTheme, string? typographySize)
    {
        var palette = ResolvePalette(typographyTheme);
        var scale = string.Equals(typographySize, CompactTypographySize, StringComparison.OrdinalIgnoreCase)
            ? 0.92d
            : 1d;

        return new MarkdownExportStyle(
            DefaultBodyFontFamily,
            DefaultMonoFontFamily,
            Scale(15, scale),
            Scale(32, scale),
            Scale(26, scale),
            Scale(22, scale),
            Scale(19, scale),
            Scale(17, scale),
            Scale(16, scale),
            Scale(13, scale),
            Scale(14, scale),
            1.55d,
            palette.PageBackground,
            palette.Body,
            palette.Heading,
            palette.Muted,
            palette.Border,
            palette.CodeBackground,
            palette.CodeForeground,
            palette.InlineCodeBackground,
            palette.InlineCodeForeground,
            palette.Link,
            palette.TableHeaderBackground,
            palette.QuoteBorder);
    }

    private static double Scale(double value, double scale)
    {
        return Math.Round(value * scale, 1);
    }

    private static ExportPalette ResolvePalette(string? typographyTheme)
    {
        return typographyTheme?.Trim().ToLowerInvariant() switch
        {
            "inkblack" or "geekblack" => new ExportPalette(
                "#111827",
                "#e5e7eb",
                "#f9fafb",
                "#cbd5e1",
                "#334155",
                "#020617",
                "#e5e7eb",
                "#1f2937",
                "#f3f4f6",
                "#93c5fd",
                "#1e293b",
                "#64748b"),
            "orangeheart" => new ExportPalette(
                "#fffaf5",
                "#2f251e",
                "#ef7060",
                "#6b5a4c",
                "#fed7aa",
                "#2f1d12",
                "#fff7ed",
                "#ffedd5",
                "#7c2d12",
                "#ef7060",
                "#fff7ed",
                "#fb923c"),
            "yamabuki" => new ExportPalette(
                "#fffdf7",
                "#3a3a3a",
                "#515151",
                "#6b6255",
                "#ffe8b3",
                "#2f2615",
                "#fff7e6",
                "#fff7e6",
                "#7a4f00",
                "#ffb11b",
                "#fff7e6",
                "#ffb11b"),
            "tendergreen" => new ExportPalette(
                "#ffffff",
                "#595959",
                "#595959",
                "#6b6b6b",
                "#d9d9d9",
                "#2f2f2f",
                "#f7f7f7",
                "#efefef",
                "#595959",
                "#595959",
                "#f5f5f5",
                "#898989"),
            "verdant" => new ExportPalette(
                "#fbfefc",
                "#1f2f27",
                "#35b378",
                "#4b6356",
                "#bbf7d0",
                "#102018",
                "#f0fdf4",
                "#dcfce7",
                "#14532d",
                "#35b378",
                "#f0fdf4",
                "#4ade80"),
            "cutegreen" => new ExportPalette(
                "#fbfefc",
                "#3f3f3f",
                "#48b378",
                "#4a4a4a",
                "#ccebd8",
                "#102018",
                "#f0fdf4",
                "#dcfce7",
                "#14532d",
                "#48b378",
                "#f0fdf4",
                "#48b378"),
            "redscarlet" => new ExportPalette(
                "#fffafa",
                "#332020",
                "#f83929",
                "#6b4a4a",
                "#fecaca",
                "#2b1212",
                "#fef2f2",
                "#fee2e2",
                "#7f1d1d",
                "#f83929",
                "#fef2f2",
                "#f87171"),
            "colorfulpurple" => new ExportPalette(
                "#fffbff",
                "#595959",
                "#773098",
                "#65556f",
                "#e9d5ff",
                "#211827",
                "#faf5ff",
                "#f3e8ff",
                "#581c87",
                "#773098",
                "#faf5ff",
                "#c084fc"),
            "rosepurple" => new ExportPalette(
                "#fffbff",
                "#595959",
                "#595959",
                "#6b5f72",
                "#eadcff",
                "#211827",
                "#faf5ff",
                "#f3e8ff",
                "#581c87",
                "#b884f6",
                "#faf5ff",
                "#dec6fb"),
            "blueglow" => new ExportPalette(
                "#f8fbff",
                "#333333",
                "#333333",
                "#475569",
                "#bfdbfe",
                "#0f172a",
                "#eff6ff",
                "#dbeafe",
                "#1e3a8a",
                "#5c9dff",
                "#eff6ff",
                "#5c9dff"),
            "technologyblue" => new ExportPalette(
                "#f8fbff",
                "#1f2937",
                "#0e88eb",
                "#475569",
                "#bfdbfe",
                "#0f172a",
                "#eff6ff",
                "#dbeafe",
                "#1e3a8a",
                "#0e88eb",
                "#eff6ff",
                "#60a5fa"),
            "lanqing" => new ExportPalette(
                "#fbfffe",
                "#1f2937",
                "#009688",
                "#475569",
                "#b7ebe5",
                "#0f172a",
                "#eaf7f5",
                "#d6efec",
                "#065f57",
                "#009688",
                "#eaf7f5",
                "#009688"),
            "fullstackblue" => new ExportPalette(
                "#f8fbff",
                "#2b2b2b",
                "#40b8fa",
                "#475569",
                "#bfdbfe",
                "#0f172a",
                "#effaff",
                "#d8f1ff",
                "#075985",
                "#40b8fa",
                "#effaff",
                "#40b8fa"),
            _ => new ExportPalette(
                "#ffffff",
                "#333333",
                "#333333",
                "#4b5563",
                "#dfe2e5",
                "#111827",
                "#f9fafb",
                "#efefef",
                "#e46918",
                "#3e64ff",
                "#f9fafb",
                "#dfe2e5")
        };
    }

    private readonly record struct ExportPalette(
        string PageBackground,
        string Body,
        string Heading,
        string Muted,
        string Border,
        string CodeBackground,
        string CodeForeground,
        string InlineCodeBackground,
        string InlineCodeForeground,
        string Link,
        string TableHeaderBackground,
        string QuoteBorder);
}
